=== VBamalie/assignment4-2/cars.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/cars" xmlns:c="http://www.example.org/cars" elementFormDefault="qualified">

    <xs:element name="cars">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="car" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="model" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="driver" type="xs:string" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                        <xs:attribute name="cid" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== VBamalie/assignment4-2/cars.xml
<!--
   New Perspectives on XML
   Tutorial 4
   Case Problem 4

   South Racing cars list
   Author: Amalie Von Behren
   Date:   06/16/2024  

   Filename:         cars.xml
   Supporting Files: cars.css
-->

<cars xmlns="http://www.example.org/cars"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://www.example.org/cars cars.xsd">
   <car cid="nes201">
      <title>Straight Away</title>
      <model>Nissan</model>
      <driver>indy</driver>
   </car>

   <car cid="gda100-5">
      <title>Quick Start</title>
      <model>General Motors</model>
      <driver>indy</driver>
   </car>

   <car cid="gma005-2">
      <title>Stop Blocks Laps</title>
      <model>Ford</model>
      <driver>indy</driver>
   </car>

   <car cid="sob-450V4">
      <title>Bendwinder</title>
      <model>Ford</model>
      <driver>412</driver>
   </car>

   <car cid="hen01-53">
      <title>Turn Twister</title>
      <model>Nissan</model>
      <driver>indy</driver>
   </car>

   <car cid="stu-050V4">
      <title>Sleeker</title>
      <model>General Motors</model>
      <driver>278</driver>
   </car>

   <car cid="dej01-003">
      <title>84 Racer</title>
      <model>General Motors</model>
      <driver>198</driver>
   </car>
</cars>
